### ISSUE TITLE
Manicotti.dll

### ISSUE THREAD

**Issue by DmitryDronovDre** [ian-quinn/manicotti#4]
Hallo.
Can you please save somewhere file : Manicotti.dll
Bacause i just dont want install visual studio only for this file
Thx

**Comment by ian-quinn** [comment]
The latest commit has the .dll and .addin files in /Demo. They are compiled for Revit 2022, which is the only version I got license for. Hope it won't bother you.

However, I have noticed that you already compiled the code :)
