### ISSUE TITLE
dll loading exception

### ISSUE THREAD

**Issue by ShehabFekry** [ian-quinn/manicotti#7]
Hello, I want to thank you for this amazing project.
I have an issue with this line as it can't load the dll file TD_Mgd_3.03_9.

` List<Util.TeighaText.CADTextModel> texts = Util.TeighaText.GetCADText(path);`

whenever I try to use the code to create openings an exception is thrown. 

here is the Exception details

![image](https://user-images.githubusercontent.com/96864483/224992878-fe398773-7f32-4e32-ad52-5b69788926c5.png)

**Comment by ian-quinn** [comment]
Sorry I have not found a perfect solution for this issue. Please refer to the answers in this thread ian-quinn/manicotti#2
Thanks for testing this toy project and hope some of its code snippets help.

**Comment by ShehabFekry** [comment]
Unfortunately I didn't find the solution either, but I think it's because the library version used is old or not compatible with new Revit API .dll files, so I removed the library and anything related to it and used another way to create doors. but in the end thank you for this great solution I've gained a lot of knowledge from it.
